signing image

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,7 +36,6 @@ env:
 # ============================================================
 
 jobs:
-
   # ----------------------------------------------------------
   # GITLEAKS
   # ----------------------------------------------------------
@@ -109,7 +108,7 @@ jobs:
           > checkov-dockerfile-report.json
         # TODO 1:  On Line 100, its making `CKV_DOCKER_2` to skip Health Check ci pipeline.
         # checkov:skip=CKV_DOCKER_2:Healthcheck is managed by the deployment platform
-        
+
       - name: Upload Checkov Reports
         if: always()
         uses: actions/upload-artifact@v7
@@ -238,7 +237,7 @@ jobs:
         uses: actions/checkout@v7
         with:
           fetch-depth: 0
-          
+
       - name: Setup Python
         uses: actions/setup-python@v7
         with:
@@ -313,76 +312,28 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v7
 
-      # --------------------------------------------------------
-      # IMAGE TAG
-      # --------------------------------------------------------
-
       - name: Generate Image Tag
         id: image-tag
         run: |
           echo "tag=${GITHUB_SHA::12}" >> "$GITHUB_OUTPUT"
           echo "tag=${GITHUB_SHA::12}"
 
-      # --------------------------------------------------------
-      # DOCKER LOGIN
-      # --------------------------------------------------------
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v4
-        with:
-          username: ${{ vars.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
-
-      # --------------------------------------------------------
-      # BUILDX
-      # --------------------------------------------------------
-
       - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v4
 
-      # --------------------------------------------------------
-      # BUILD IMAGE
-      # --------------------------------------------------------
-
+        # Build Image Locally and don't push
       - name: Build Docker Image
         uses: docker/build-push-action@v7
         with:
           context: .
-          load: true
+          load: true # don't push now
           push: false
 
           tags: |
             ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
-            ${{ env.IMAGE_NAME }}:qa
 
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
-      # --------------------------------------------------------
-      # VERIFY PYTHON PACKAGES INSIDE IMAGE
-      # --------------------------------------------------------
-
-      - name: Verify Python Package Versions
-        run: |
-          docker run --rm \
-            ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }} \
-            python -c "
-          import msgpack
-          import setuptools
-          import urllib3
-
-          print('msgpack:', msgpack.__version__)
-          print('setuptools:', setuptools.__version__)
-          print('urllib3:', urllib3.__version__)
-
-          assert tuple(map(int, msgpack.__version__.split('.'))) >= (1, 2, 1)
-          assert tuple(map(int, setuptools.__version__.split('.'))) >= (78, 1, 1)
-          assert tuple(map(int, urllib3.__version__.split('.'))) >= (2, 8, 0)
-          "
-
-      # --------------------------------------------------------
-      # TRIVY IMAGE SCAN
-      # --------------------------------------------------------
 
       - name: Setup Trivy
         uses: aquasecurity/setup-trivy@v0.3.1
@@ -393,15 +344,10 @@ jobs:
       - name: Scan Docker Image
         run: |
           trivy image \
-            --scanners vuln \
             --ignore-unfixed \
             --severity HIGH,CRITICAL \
             --exit-code 1 \
-            ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
-
-      # --------------------------------------------------------
-      # IMAGE SBOM
-      # --------------------------------------------------------
+            "${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}"
 
       - name: Generate Image SBOM
         if: always()
@@ -410,7 +356,7 @@ jobs:
             --format cyclonedx \
             --output image-sbom-cyclonedx.json \
             --exit-code 0 \
-            ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
+            "${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}"
 
       - name: Upload Image SBOM
         if: always()
@@ -421,11 +367,56 @@ jobs:
           if-no-files-found: warn
           archive: false
 
-      # --------------------------------------------------------
-      # PUSH IMAGE
-      # --------------------------------------------------------
+      - name: Login to Docker Hub
+        uses: docker/login-action@v4
+        with:
+          username: ${{ vars.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
       - name: Push Docker Image
         run: |
           docker push \
-            ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
+            "${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}"
+
+      # After pushing to docker registery get Immutable Registry Digest
+      - name: Get Immutable Registry Digest of Image
+        id: image-digest
+        run: |
+          DIGEST=$(docker inspect \
+            --format='{{index .RepoDigests 0}}' \
+            "${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}" \
+            | cut -d'@' -f2)
+
+          if [ -z "$DIGEST" ]; then
+            echo "Failed to obtain image digest"
+            exit 1
+          fi
+          echo "Image digest: $DIGEST"
+          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
+
+  sign:
+    name: Sign Container Image
+    runs-on: ubuntu-latest
+
+    needs:
+      - docker
+
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@v3
+
+      - name: Sign Image
+        env:
+          IMAGE: ${{ env.IMAGE_NAME }}
+          DIGEST: ${{ steps.image-digest.outputs.digest }}
+        run: |
+          echo "Signing:"
+          echo "${IMAGE}@${DIGEST}"
+
+          cosign sign \
+            --yes \
+            "${IMAGE}@${DIGEST}"
